#SPDX-License-Identifier: MIT-0
---
# tasks file for jenkins
- name: Install Java
  ansible.builtin.yum:
    name: java-17-amazon-corretto
    state: present

- name: Add jenkins to the repo
  ansible.builtin.get_url:
    url: https://pkg.jenkins.io/redhat-stable/jenkins.repo
    dest: /etc/yum.repos.d/jenkins.repo
  

- name: Import Jenkins GPG key
  ansible.builtin.rpm_key:
    key: https://pkg.jenkins.io/redhat-stable/jenkins.io-2023.key
    state: present
  become: true

- name: Install Jenkins
  ansible.builtin.yum:
    name: jenkins
    state: present

- name: Start and enable Jenkins
  ansible.builtin.service:
    name: jenkins
    state: started
    enabled: true

- name: Install Python security tools
  ansible.builtin.pip:
    name:
      - checkov
      - detect-secrets
    executable: pip3

- name: Install tflint
  ansible.builtin.shell: curl -s https://raw.githubusercontent.com/terraform-linters/tflint/master/install_linux.sh | bash
  args:
    creates: /usr/local/bin/tflint

- name: Install yum-utils and shadow-utils
  ansible.builtin.yum:
    name:
      - yum-utils
      - shadow-utils
    state: present

- name: Add Hashicorp repository 
  ansible.builtin.get_url:
    url: https://rpm.releases.hashicorp.com/AmazonLinux/hashicorp.repo
    dest: /etc/yum.repos.d/hashicorp.repo
    mode: '0644'

- name: Install Terraform
  ansible.builtin.yum:
    name:
      - terraform
    state: present