#SPDX-License-Identifier: MIT-0
---
# tasks file for app
- name: Install Java
  ansible.builtin.yum:
    name: java-17-amazon-corretto
    state: present

- name: Create the app directory
  ansible.builtin.file:
    path: /opt/votingapp
    state: directory
    mode: '0755'

- name: Copy the jar file from jenkins to tomcat
  ansible.builtin.copy:
    src: "{{ jar_file }}"
    dest: /opt/votingapp/votingapp.jar
  
- name: Restart Tomcat
  ansible.builtin.service:
    name: tomcat
    state: restarted
    enabled: true
    