
---
- name: Configure EC2 instance
  hosts: app_servers
  become: true
  roles:
    - common
    - app_server
   
   # - jenkins (removing jenkins because i'll be manually setting up the
   # ec2 for jenkins to run...git)